### PR TITLE
File image previews

### PR DESCRIPTION
**Pull request by vzqzac**
What does this change?
------

Addresses #33 to show file preview images

How did you accomplish it?
------

- Added mini_magick to handle image manipulation when creating previews with active storage
- Created a couple of helper methods to check if a file is _previewable_ and get the source of the preview

Screenshots
------
**Image file:**
image

**PDF:**
image

**Video:**
image

### CODE REVIEW

**Comment by VzqzAc** [comment]
🤔 seems like the failures are because of the PDF file sample not being loaded

**Comment by VzqzAc** [comment]
@MatheusRich the problem is the pdf file, I'm not sure if it's being blacklisted or if we need to add `poppler` to the CI

**Comment by MatheusRich** [comment]
@VzqzAc I've tested your branch here and I couldn't see the video preview. Plus, the preview shouldn't be presented by default. It's better keep it hidden and add a button to toggle it.

**Comment by VzqzAc** [comment]
Yeah you need to install some tools to generate previews for videos and
PDFs (I think that's the problem in the CI), I'll add some documentation
for that, and I'll modify the behavior too 👍

**Comment by VzqzAc** [comment]
@MatheusRich I cherry-picked the commits to add the needed tools to Travis in this PR, once we merge #71 they will go away :)

**Pull request closed without merging**
