### PR TITLE
Adds Docker Environment

### LINKED ISSUE #3: Add docker environment

### PR DESCRIPTION
**Pull request by MatheusRich**
Fixes #3

### CODE REVIEW

**Comment by MatheusRich** [comment]
@alaxalves Can you give some feedback about this?

**Comment by alaxalves** [comment]
Hey @MatheusRich I had some trouble with my environment, but I'm curently reviewing this. I'll give some feedback soon.

**Comment by alaxalves** [comment]
Hey @MatheusRich it worked like a charm for me, but I see some things that you could improve. Do you want to make those changes or do you want to do 'em by yourself?

**Comment by MatheusRich** [comment]
@alaxalves I'll merge this PR and you can make the improvements and send another one.

**Pull request merged**
