### PR TITLE
Cleanup style for buttons

### PR DESCRIPTION
**Pull request by VzqzAc**
### What does this implement/fix? ###

The buttons sylesheet had a TODO part of code that was now unnecesary
since we'll rely on the `button` class. This also adds that class to
the delete button on the file

### Does this close any currently open issues? ###

No

### CODE REVIEW

**Comment by MatheusRich** [comment]
@VzqzAc I wrote this comment to remember myself to make this html/css right. On `show.html.erb` you can see that one button is a link and other is a real button tag. Can you make both links or buttons?

**Comment by MatheusRich** [comment]
@VzqzAc are you still up for this?

**Comment by VzqzAc** [comment]
Yes @MatheusRich, I'll tackle it this weekend, it has been a busy week at work

**Comment by MatheusRich** [comment]
@VaqzAc My bad! I didn't want to bother. There's some nice work that you've done, so I didn't want to lose it. I'm here for any help you want to. Take your time!

**Comment by VzqzAc** [comment]
Not bothering at all! Also about this PR, @MatheusRich I think it should remain as is, keeping so under the following premise:
> Buttons Do Things, Links Go Places

It should remain a link I think, just with a button-ish design, also, I could change the parent id from `buttons` to `actions` in order to have a proper description of what the contet is, what do you think?

https://css-tricks.com/building-good-download-button/

**Comment by MatheusRich** [comment]
@VzqzAc Thanks! Merged!

**Pull request merged**
