### PR TITLE
Upgrade to Rails 5.2.2

### LINKED ISSUE #80: CC reporter cant find formatter
### Expected behavior
CC should find simplecov as its formatter

### Current behavior
image

### Steps to reproduce the behavior
Find it at ny Travis CI build

### Your Environment

* Version used: ?
* Browser Name and version: Google Chrome
* Operating System and version (desktop or mobile): Linux Mint 18.1
* Link to your project: https://github.com/alaxalves/dontfile/

### PR DESCRIPTION
**Pull request by alaxalves**
### What does this implement/fix? ###
Updates app to Rails 5.2.2, fixes #80 and improves CI

### CODE REVIEW

**Comment by alaxalves** [comment]
Apparently your task `bundle exec rails db:migrate RAILS_ENV=test` in .travis.yml is creating a new schema.rb file everytime there is a build, causing rubocop to break. How should I proceed?

**Comment by MatheusRich** [comment]
I'm not sure why this is happening. Could you verify this?

**Comment by alaxalves** [comment]
@MatheusRich It's fixed!! :raised_hands:

**Comment by MatheusRich** [comment]
@alaxalves Thanks! Merged!

**Pull request merged**
